// =============================================================================
// models/Interview.js — MongoDB Interview Schema
// =============================================================================
// Purpose  : Defines the structure of an "Interview" document in MongoDB.
//            Each time a user completes an interview, one document is created
//            with their answers, AI scores, and feedback.
//
// Used by  : - api/evaluate/route.js (creates new documents after scoring)
//            - app/results/[id]/page.js (reads documents to display feedback)
//            - app/dashboard/page.js (lists all interviews for the logged-in user)
//
// Relation : Each Interview belongs to one User via the 'userId' field
//            (similar to a foreign key in SQL databases)
// =============================================================================

import mongoose, { Schema, models } from 'mongoose';

// ─── Question Sub-Schema ──────────────────────────────────────────────────────
// This defines the structure of a SINGLE question within an interview.
// It's used as an array type inside the main interviewSchema below.
// Think of it as a "nested document" — MongoDB stores it inside the interview.
const questionSchema = new Schema({
  questionText: {
    type: String,
    required: true,   // The actual interview question text (generated by Gemini AI)
  },
  userAnswer: {
    type: String,
    // Not required — users might skip a question or leave it blank
  },
  aiScore: {
    type: Number,
    // Score out of 10 assigned by the Gemini AI evaluation (see api/evaluate/route.js)
  },
  aiFeedback: {
    type: String,
    // The detailed feedback paragraph from Gemini about this specific answer
  }
});

// ─── Interview Schema ─────────────────────────────────────────────────────────
// The top-level document structure saved to MongoDB's "interviews" collection
const interviewSchema = new Schema(
  {
    userId: {
      // Links this interview to its owner in the 'users' collection.
      // mongoose.Schema.Types.ObjectId is MongoDB's unique ID type.
      // 'ref: User' enables Mongoose's .populate() to fetch user data if needed.
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },
    role: {
      // The job role the user selected on the setup page (e.g., 'Frontend Developer')
      type: String,
      required: true,
    },
    difficulty: {
      type: String,
      default: 'Medium',  // 'Easy' | 'Medium' | 'Hard'
    },
    category: {
      type: String,
      default: 'General', // 'React' | 'Node.js' | 'DSA' | 'System Design' | 'General'
    },
    totalScore: {
      // The overall average score across all questions (calculated in api/evaluate/route.js)
      type: Number,
      default: 0,
    },
    questions: {
      // An array of the question sub-documents defined in questionSchema above
      type: [questionSchema],
      default: [],
    }
  },
  {
    // 'createdAt' is especially important — used to display the interview date on the dashboard
    timestamps: true,
  }
);

// ─── Export ──────────────────────────────────────────────────────────────────
// Guard against Next.js hot-reload OverwriteModelError
const Interview = models.Interview || mongoose.model('Interview', interviewSchema);

export default Interview;
